# STOCK AND OPTIONS PRESENTATION FEATURES




References:

[Alpaca API Docs](https://alpaca.markets/docs/api-documentation/)

[Pandas pie plot](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.pie.html)

## Import the required libraries and dependencies

In [444]:
# Import the required libraries and dependencies
import os
import requests
import pandas as pd
import numpy as np
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
%matplotlib inline

## Step 1: Create your environment file (`.env`) in your project folder. Make sure that this file holds your Alpaca API and secret keys.

## Step 2: Import the Alpaca API and secret keys into the `investment_valuations.ipynb` notebook.

* Load the environment variable by calling the `load_dotenv()` function.
* Set the value of the variables `alpaca_api_key` and `alpaca_secret_key` equal to their respective environment variables. 
* Confirm the variables are available by checking the `type` of each.

In [445]:
# Load the environment variables by calling the load_dotenv function
load_dotenv()

True

In [446]:
# Set Alpaca API key and secret by calling the os.getenv function and referencing the environment variable names
# Set each environment variable to a notebook variable of the same name
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

# Check the values were imported correctly by evaluating the type of each
display(type(alpaca_api_key))
display(type(alpaca_secret_key))

str

str

## Step 3: Create the Alpaca API `REST` object by calling the Alpaca `tradeapi.REST` function and then setting the `alpaca_api_key`, `alpaca_secret_key`, and `api_version`.

In [447]:
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2",
    )

## WE COULD ADD IN A CALL TO STREAMLIT HERE FOR A TICKER SYMBOL.

In [448]:
# Set current amount of shares data

# shares_data = {
#    "shares": [200, 320]


# Set the tickers
tickers = ["CCL"]

# Create the shares DataFrame
#portfolio_df = pd.DataFrame(shares_data, index=tickers)

# Display shares data
#portfolio_df

## Step 5: Get the closing prices of the prior business day for the two stocks in question, Apple and Microsoft, by using the Alpaca `get_bars` function. Note that this requires values for `tickers`, `timeframe`, and the `start` and `end` dates. Add the `df` property to the end of this API call to automatically convert the response to a DataFrame.

* Confirm the value for `tickers` from a the prior step
* Set the values for `start_date` and `end_date` using the `pd.Timestamp` function.
* Set the `timeframe` value to 1 day.
* Create the `portfolio_prices_df` DataFrame by setting it equal to the `alpaca.get_bars` function.

In [449]:
# Confirm the values of the  tickers variable created in the prior step
tickers

['CCL']

In [450]:
# Set the values for start_date and end_date using the pd.Timestamp function
# Inside the function set the date parameter to the prior business day 
# Both the start_date and end_date should contain the same date valuloe, as we looking for the closing price
# of the prior business day
# Set the parameter tz to "America/New_York", 
# Set this all to the ISO format by calling the isoformat function 

start_date = pd.Timestamp("2015-06-15", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2022-08-15", tz="America/New_York").isoformat()

In [451]:
# Set timeframe to one day (1Day) for the Alpaca API
timeframe = "1Day"

In [498]:
# Use the Alpaca get_bars function to gather the price information for each ticker
# Include the function parameters: tickers, timeframe, start, and end
# Be sure to call the df property to ensure that the returned information is set as a DataFrame
portfolio_prices_df = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date,
    end = end_date
).df

# Preview the resulting `portfolio_prices_df` DataFrame. 
portfolio_prices_df.head()

,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,
2015-12-01 05:00:00+00:00,51.15,51.530,50.795,51.46,5052267,25392,51.232917,CCL
2015-12-02 05:00:00+00:00,51.45,51.660,51.070,51.18,3015632,25891,51.343536,CCL
2015-12-03 05:00:00+00:00,51.43,51.480,49.145,49.31,4995077,37736,49.938485,CCL
2015-12-04 05:00:00+00:00,49.78,50.760,49.740,50.69,4126341,31788,50.381126,CCL
2015-12-07 05:00:00+00:00,51.01,51.255,50.280,50.67,3566843,28430,50.720807,CCL

In [453]:
# Reorganize the DataFrame
# Separate ticker data
CCL = portfolio_prices_df[portfolio_prices_df['symbol']=='CCL'].drop('symbol', axis=1)


CCL = CCL.drop(['open', 'high', 'low', 'volume', 'trade_count', 'vwap'], axis = 1) 

#CCL = CCL.insert(1,"std", int)
CCL_standard_dev = CCL.std()*np.sqrt(252)

# Concatenate the ticker DataFrames
#portfolio_prices_df = pd.concat([CCL, SPX],axis=1, keys=['CCL','SPX'])

# Display sample data
display(CCL_standard_dev)

close    298.914796
dtype: float64

In [454]:
CCL["std"] = CCL["close"].std()
CCL["Percent_change"] = CCL["close"].pct_change()
CCL = CCL.dropna()

CCL

                           close        std  Percent_change
timestamp
2015-12-02 05:00:00+00:00  51.18  18.829862       -0.005441
2015-12-03 05:00:00+00:00  49.31  18.829862       -0.036538
2015-12-04 05:00:00+00:00  50.69  18.829862        0.027986
2015-12-07 05:00:00+00:00  50.67  18.829862       -0.000395
2015-12-08 05:00:00+00:00  50.16  18.829862       -0.010065
...                          ...        ...             ...
2022-08-09 04:00:00+00:00   9.47  18.829862       -0.053946
2022-08-10 04:00:00+00:00  10.34  18.829862        0.091869
2022-08-11 04:00:00+00:00  10.54  18.829862        0.019342
2022-08-12 04:00:00+00:00  10.72  18.829862        0.017078
2022-08-15 04:00:00+00:00  10.71  18.829862       -0.000933

[1688 rows x 3 columns]

In [455]:
#Calculate volatility of the underlying stock - a proxy for implied
# volatility
import numpy as np
CCL['Log returns'] = np.log(CCL['close']/CCL['close'].shift())
CCL['Log returns'] = pd.to_numeric(CCL['Log returns'])

volatility = CCL['Log returns'].std()*252**.5
volatility_float = float(volatility)
volatility_float

0.5994142503337853

In [456]:
CCL.dropna()

                           close        std  Percent_change  Log returns
timestamp
2015-12-03 05:00:00+00:00  49.31  18.829862       -0.036538    -0.037222
2015-12-04 05:00:00+00:00  50.69  18.829862        0.027986     0.027602
2015-12-07 05:00:00+00:00  50.67  18.829862       -0.000395    -0.000395
2015-12-08 05:00:00+00:00  50.16  18.829862       -0.010065    -0.010116
2015-12-09 05:00:00+00:00  50.31  18.829862        0.002990     0.002986
...                          ...        ...             ...          ...
2022-08-09 04:00:00+00:00   9.47  18.829862       -0.053946    -0.055456
2022-08-10 04:00:00+00:00  10.34  18.829862        0.091869     0.087891
2022-08-11 04:00:00+00:00  10.54  18.829862        0.019342     0.019158
2022-08-12 04:00:00+00:00  10.72  18.829862        0.017078     0.016934
2022-08-15 04:00:00+00:00  10.71  18.829862       -0.000933    -0.000933

[1687 rows x 4 columns]

In [5]:
#API call from rapidapi.com for CCL
import requests
import os
import requests
import pandas as pd
import numpy as np
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
%matplotlib inline
import streamlit as st

st.title('Options Chain')
st.header('Company Information')


input_ticker = st.text_input('Enter a stock symbol (all caps please)')
id = input_ticker
url = "https://option-chain.p.rapidapi.com/options/%s" % id 
print(url)

input_ticker = st.text_input('Enter a stock symbol (all caps please)')
st.write(input_ticker)
#url = "https://option-chain.p.rapidapi.com/options/CCL"

headers = {
	"X-RapidAPI-Key": "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",
	"X-RapidAPI-Host": "option-chain.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

#print(response.text)

https://option-chain.p.rapidapi.com/options/

In [2]:
r = response.json()
p = r["options"][0]['2022-08-26']['calls']
#convert python dictionary to dataframe
#Chain = pd.DataFrame.from_dict(r, orient = "index", columns=['date','strike', 'symbol', 'last'])
#Chain.head()
df = pd.DataFrame(p)
df

KeyError: 'options'

In [ ]:
r = response.json()
p = r["options"][0]['2022-08-26']['puts']
#convert python dictionary to dataframe
#Chain = pd.DataFrame.from_dict(r, orient = "index", columns=['date','strike', 'symbol', 'last'])
#Chain.head()
df1 = pd.DataFrame(p)
df1

,symbol,strike,last,bid,ask,open interest,volume,change,percentChange,iv
0,CCL220826P00003000,3.0,0.04,0.00,0.03,1.0,1.0,0.00,0.00,5.1250
1,CCL220826P00003500,3.5,0.03,0.00,0.03,2.0,1.0,0.00,0.00,4.5000
2,CCL220826P00004000,4.0,0.02,0.00,0.01,584.0,5.0,0.00,0.00,3.3750
3,CCL220826P00004500,4.5,0.02,0.00,0.01,112.0,11.0,0.00,0.00,3.0000
4,CCL220826P00005000,5.0,0.01,0.00,0.01,361.0,5.0,0.00,0.00,2.6250
5,CCL220826P00005500,5.5,0.01,0.00,0.01,2041.0,92.0,0.00,0.00,2.2500
6,CCL220826P00006000,6.0,0.02,0.00,0.01,318.0,9.0,0.00,0.00,1.8750
7,CCL220826P00006500,6.5,0.01,0.00,0.02,639.0,1.0,0.00,0.00,1.7500
8,CCL220826P00007000,7.0,0.01,0.00,0.01,750.0,1.0,0.00,0.00,1.3125
9,CCL220826P00007500,7.5,0.01,0.00,0.01,3568.0,21.0,-0.01,-50.00,1.0625
10,CCL220826P00008000,8.0,0.02,0.01,0.03,1308.0,55.0,0.00,0.00,1.0313
11,CCL220826P00008500,8.5,0.03,0.02,0.03,2175.0,447.0,-0.03,-50.00,0.7656
12,CCL220826P00009000,9.0,0.08,0.07,0.08,3230.0,3214.0,-0.08,-50.00,0.6719
13,CCL220826P00009500,9.5,0.23,0.23,0.24,4254.0,1068.0,-0.14,-37.84,0.6406
14,CCL220826P00010000,10.0,0.57,0.55,0.58,21680.0,291.0,-0.13,-18.57,0.6797
15,CCL220826P00010500,10.5,0.98,0.98,1.06,1766.0,38.0,-0.16,-14.04,0.8359
16,CCL220826P00011000,11.0,1.47,1.45,1.51,850.0,82.0,-0.14,-8.70,0.8438
17,CCL220826P00011500,11.5,2.12,1.94,2.01,209.0,53.0,0.00,0.00,0.9844
18,CCL220826P00012000,12.0,2.50,2.44,2.53,275.0,1.0,-0.12,-4.58,1.2813
19,CCL220826P00012500,12.5,2.88,2.93,3.05,64.0,12.0,0.23,8.68,1.5000
20,CCL220826P00013000,13.0,3.50,3.40,3.50,6.0,1.0,0.80,29.63,1.7656
21,CCL220826P00013500,13.5,3.68,3.90,4.05,8.0,5.0,0.00,0.00,1.6250
22,CCL220826P00014000,14.0,4.17,4.40,4.50,113.0,145.0,0.00,0.00,2.0938
23,CCL220826P00014500,14.5,4.68,4.90,5.00,7.0,2.0,0.00,0.00,2.2344
24,CCL220826P00015000,15.0,4.60,5.40,5.50,5.0,1.0,0.00,0.00,2.3750
25,CCL220826P00016000,16.0,5.40,6.40,6.55,27.0,1.0,0.00,0.00,2.2500
26,CCL220826P00017000,17.0,6.98,7.40,7.50,3.0,2.0,0.00,0.00,2.8750
27,CCL220826P00018000,18.0,7.55,8.40,8.55,0.0,5.0,0.00,0.00,2.6875

In [ ]:
"""
options_chain = pd.concat(df, df1)
options_chain
"""

'\noptions_chain = pd.concat(df, df1)\noptions_chain\n'

In [ ]:
"""
from pathlib import Path
Sept2_call_price_CCL = pd.read_csv(Path("./CSV/Sept_2.csv"),
    index_col="Last Trade Date",
    parse_dates=True, 
    infer_datetime_format=True,
    #usecols=['Strike'],
    #dtype={'Strike': np.float64},
)

Sept2_call_price_CCL.head()

#Aug19_call_price_CCL = 
"""

'\nfrom pathlib import Path\nSept2_call_price_CCL = pd.read_csv(Path("./CSV/Sept_2.csv"),\n    index_col="Last Trade Date",\n    parse_dates=True, \n    infer_datetime_format=True,\n    #usecols=[\'Strike\'],\n    #dtype={\'Strike\': np.float64},\n)\n\nSept2_call_price_CCL.head()\n\n#Aug19_call_price_CCL = \n'

In [ ]:
"""
Sept2_call_price_CCL = pd.DataFrame(
    {
        "Strike": pd.Series(["Strike"], dtype=np.dtype("float")),
        }
)

Sept2_call_price_CCL
"""

'\nSept2_call_price_CCL = pd.DataFrame(\n    {\n        "Strike": pd.Series(["Strike"], dtype=np.dtype("float")),\n        }\n)\n\nSept2_call_price_CCL\n'

In [ ]:
"""
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
enc.fit(Sept2_call_price_CCL['Strike'])
Sept2_call_price_CCL['Strike'] = enc.transform(Sept2_call_price_CCL['Strike'])
Sept2_call_price_CCL['Strike'] = Sept2_call_price_CCL['Strike'].astype(float)
Sept2_call_price_CCL
"""

"\nfrom sklearn.preprocessing import LabelEncoder\nenc = LabelEncoder()\nenc.fit(Sept2_call_price_CCL['Strike'])\nSept2_call_price_CCL['Strike'] = enc.transform(Sept2_call_price_CCL['Strike'])\nSept2_call_price_CCL['Strike'] = Sept2_call_price_CCL['Strike'].astype(float)\nSept2_call_price_CCL\n"

In [ ]:
#Sept2_call_price_CCL["Strike"] = Sept2_call_price_CCL["Strike"].float()

In [ ]:
#Sept2_call_price_CCL.head()

In [ ]:
df = df.drop(['bid', 'ask', 'change', 'percentChange', 'volume', 'open interest'], axis = 1)
#Aug19_call_price_CCL = Aug19_call_price_CCL.drop(['Bid', 'Ask', 'Change', '% Change', 'Volume', 'Open Interest'], axis = 1, inplace = True)
display(df)

                symbol  strike  last      iv
0   CCL220826C00003500     3.5  6.56  4.2500
1   CCL220826C00004000     4.0  5.55  3.6875
2   CCL220826C00004500     4.5  5.55  3.2500
3   CCL220826C00005000     5.0  4.80  2.8125
4   CCL220826C00005500     5.5  4.25  2.4375
5   CCL220826C00006000     6.0  4.60  2.0625
6   CCL220826C00006500     6.5  4.60  1.7500
7   CCL220826C00007000     7.0  2.61  1.3125
8   CCL220826C00007500     7.5  2.14  1.2500
9   CCL220826C00008000     8.0  1.57  0.9063
10  CCL220826C00008500     8.5  1.08  0.8125
11  CCL220826C00009000     9.0  0.63  0.6719
12  CCL220826C00009500     9.5  0.28  0.6641
13  CCL220826C00010000    10.0  0.11  0.6797
14  CCL220826C00010500    10.5  0.05  0.7656
15  CCL220826C00011000    11.0  0.02  0.8750
16  CCL220826C00011500    11.5  0.02  0.9844
17  CCL220826C00012000    12.0  0.01  1.1563
18  CCL220826C00012500    12.5  0.01  1.1250
19  CCL220826C00013000    13.0  0.01  1.2500
20  CCL220826C00013500    13.5  0.02  1.5313
21  CCL220826C00014000    14.0  0.02  1.6875
22  CCL220826C00014500    14.5  0.01  1.6250
23  CCL220826C00015000    15.0  0.01  1.7500
24  CCL220826C00015500    15.5  0.01  1.8750
25  CCL220826C00016000    16.0  0.01  1.9375
26  CCL220826C00017000    17.0  0.02  2.3750
27  CCL220826C00017500    17.5  0.02  2.4375

In [ ]:
df.dtypes

symbol     object
strike    float64
last      float64
iv        float64
dtype: object

## Formulate and apply Black Scholes Merton model to Call and Put prices

C – Call option price
P – Put option price
S – Stock price
K – Strike price
r – risk-free rate
t – time to expiration in years
σ – volatility
N() – the standard normal cumulative distribution function

Call price = N(d1)*S - N(d2)*K*EXP(-rt)
Put price = N(-d2)*K*EXP(-rt) - N(-d1)*S

d1 = (log(S/K) + (r + σ^2/2)*t) / σ*t^.5
d2 = d1 - σ*t^.5

1. Calculate volatility of the stock price (done above)
2. Calculate d1
3. Calculate d2
4. Calculate Call price
5. Calculate Put price
6. Compare against actual price
7. present all dislocations as $/contract -> 100 shares in 1 contract

In [ ]:
#To calculate the time to expiration
from datetime import date
import arrow
today = arrow.get("2022-08-16").float_timestamp
print(today)

1660608000.0

In [ ]:
#User input: What is the expiration date (YYYY-MM-DD)
"""
NOTE questionary must be run from a terminal

import questionary
expiration_date = questionary.text("What's is the expiration date of contract?").ask()
expiration_date
"""

'\nNOTE questionary must be run from a terminal\n\nimport questionary\nexpiration_date = questionary.text("What\'s is the expiration date of contract?").ask()\nexpiration_date\n'

In [ ]:
"""
expiration_date = input('What is the expiration date (YYYY-MM-DD): ')
print(expiration_date)
"""
from datetime import date
import arrow
fmt = "YYYY-MM-DD"
expiration_date = arrow.get('2022-09-02').float_timestamp
print(expiration_date)

1662076800.0

In [ ]:
#Calculate days to expiration
#Because of the time lag and working with a fixed CSV, I've made the "current date"
# Aug 16, 2022 and the expiration date Sept 2, 2022. 
time = expiration_date - today

#actual days are 3 days - timestamp must be in seconds

DBD = time/(60*60*24)
print(DBD)

17.0

In [ ]:
#Risk free rate is the 3 month WSJ quoted T-bill
#https://www.wsj.com/market-data/bonds/keyinterestrates
Risk_free_rate = float(.0255)
print(Risk_free_rate)

0.0255

In [ ]:
# Stock price as of the day the options CSV's were pulled
Stock_price = float(11.43)
display(Stock_price)

11.43

In [ ]:
df['strike'].dtype

dtype('float64')

In [ ]:
import math
math.log(Stock_price)
Risk_free_rate
volatility_float
DBD

17.0

In [ ]:
df["d1a"] = Stock_price/df['strike']
df

                symbol  strike  last      iv       d1a
0   CCL220826C00003500     3.5  6.56  4.2500  3.265714
1   CCL220826C00004000     4.0  5.55  3.6875  2.857500
2   CCL220826C00004500     4.5  5.55  3.2500  2.540000
3   CCL220826C00005000     5.0  4.80  2.8125  2.286000
4   CCL220826C00005500     5.5  4.25  2.4375  2.078182
5   CCL220826C00006000     6.0  4.60  2.0625  1.905000
6   CCL220826C00006500     6.5  4.60  1.7500  1.758462
7   CCL220826C00007000     7.0  2.61  1.3125  1.632857
8   CCL220826C00007500     7.5  2.14  1.2500  1.524000
9   CCL220826C00008000     8.0  1.57  0.9063  1.428750
10  CCL220826C00008500     8.5  1.08  0.8125  1.344706
11  CCL220826C00009000     9.0  0.63  0.6719  1.270000
12  CCL220826C00009500     9.5  0.28  0.6641  1.203158
13  CCL220826C00010000    10.0  0.11  0.6797  1.143000
14  CCL220826C00010500    10.5  0.05  0.7656  1.088571
15  CCL220826C00011000    11.0  0.02  0.8750  1.039091
16  CCL220826C00011500    11.5  0.02  0.9844  0.993913
17  CCL220826C00012000    12.0  0.01  1.1563  0.952500
18  CCL220826C00012500    12.5  0.01  1.1250  0.914400
19  CCL220826C00013000    13.0  0.01  1.2500  0.879231
20  CCL220826C00013500    13.5  0.02  1.5313  0.846667
21  CCL220826C00014000    14.0  0.02  1.6875  0.816429
22  CCL220826C00014500    14.5  0.01  1.6250  0.788276
23  CCL220826C00015000    15.0  0.01  1.7500  0.762000
24  CCL220826C00015500    15.5  0.01  1.8750  0.737419
25  CCL220826C00016000    16.0  0.01  1.9375  0.714375
26  CCL220826C00017000    17.0  0.02  2.3750  0.672353
27  CCL220826C00017500    17.5  0.02  2.4375  0.653143

In [ ]:
#for df['strike'] 
for strike in range(0, len(df['strike'])):
    df['dialog'] = math.log(['d1a'])
#df['d1alog'] = math.log(df['d1a'])
df

TypeError: must be real number, not list

In [ ]:
# Calculate d1 = (log(S/K) + (r + σ^2/2)*t) / σ*t^.5
import math 
g = (math.log((Stock_price)/(df["strike"])) + (Risk_free_rate + volatility_float**2/2)*DBD)/(volatility_float*DBD**.5)
#denominator = (volatility_float*DBD**.5)
print(g)

TypeError: cannot convert the series to <class 'float'>

In [ ]:
# Fetch the current closing prices for Apple and Microsoft from the portfolio_prices_df DataFrame 
# Remember that the DataFrame generated from the Alpaca call incorporates multi-indexing 
# Be sure to set the values from the DataFrame to a float by calling the float function 
ccl_price = float(portfolio_prices_df["CCL"]["close"])
SPX_price = float(portfolio_prices_df["SPY"]["close"])

print(ccl_price)
print(SPX_price)

KeyError: 'CCL'

In [ ]:
"""
import http.client

conn = http.client.HTTPSConnection("option-chain.p.rapidapi.com")

headers = {
    'X-RapidAPI-Key': "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",
    'X-RapidAPI-Host': "option-chain.p.rapidapi.com"
    }

conn.request("GET", "/options/CCL", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

CCL_Options_data = pd.DataFrame(data.decode("utf-8"))
"""

'\nimport http.client\n\nconn = http.client.HTTPSConnection("option-chain.p.rapidapi.com")\n\nheaders = {\n    \'X-RapidAPI-Key\': "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",\n    \'X-RapidAPI-Host\': "option-chain.p.rapidapi.com"\n    }\n\nconn.request("GET", "/options/CCL", headers=headers)\n\nres = conn.getresponse()\ndata = res.read()\n\nprint(data.decode("utf-8"))\n\nCCL_Options_data = pd.DataFrame(data.decode("utf-8"))\n'

In [ ]:
"""
import requests

url = "https://option-chain.p.rapidapi.com/options/CCL"

headers = {
	"X-RapidAPI-Key": "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",
	"X-RapidAPI-Host": "option-chain.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

print(response.text)
"""

'\nimport requests\n\nurl = "https://option-chain.p.rapidapi.com/options/CCL"\n\nheaders = {\n\t"X-RapidAPI-Key": "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",\n\t"X-RapidAPI-Host": "option-chain.p.rapidapi.com"\n}\n\nresponse = requests.request("GET", url, headers=headers)\n\nprint(response.text)\n'

In [ ]:
import requests

url = "https://option-chain.p.rapidapi.com/options/CCL"

headers = {
	"X-RapidAPI-Key": "e17dcce559msh919faee0afa4c7bp1ce1a6jsn70cc4d9ff538",
	"X-RapidAPI-Host": "option-chain.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

#Options = response(["Options":[0: ]})

#print(Options)

#response_df = pd.DataFrame.from_dict(response,orient='index')

#response_df

#print(response.text)

In [ ]:
Options_ALL = pd.DataFrame(Body: Options)

#[[0:{"2022-08-26":{"calls":[...],"puts":[...]})

""""""
}
1:{...}1 item
2:{...}1 item
3:{...}1 item
4:{...}1 item
5:{...}1 item]")

"""
print(Options_ALL)

SyntaxError: invalid syntax (3489504760.py, line 6)

In [ ]:
response.json().keys()

dict_keys(['stock', 'options'])

In [ ]:
r = response.json()
p = r["options"][0]['2022-08-26']['calls']
#convert python dictionary to dataframe
#Chain = pd.DataFrame.from_dict(r, orient = "index", columns=['date','strike', 'symbol', 'last'])
#Chain.head()
df = pd.DataFrame(p)
df

,symbol,strike,last,bid,ask,open interest,volume,change,percentChange,iv
0,CCL220826C00003500,3.5,6.56,6.10,6.15,1.0,1.0,0.00,0.00,5.3438
1,CCL220826C00004000,4.0,5.55,5.55,5.65,2.0,5.0,-0.30,-5.13,4.1250
2,CCL220826C00004500,4.5,5.55,5.05,5.15,1.0,1.0,0.00,0.00,3.5625
3,CCL220826C00005000,5.0,4.80,4.55,4.70,22.0,20.0,0.00,0.00,3.6250
4,CCL220826C00005500,5.5,4.25,4.05,4.15,22.0,1.0,-0.60,-12.37,2.7188
5,CCL220826C00006000,6.0,4.60,3.55,3.70,33.0,21.0,0.00,0.00,2.7188
6,CCL220826C00006500,6.5,4.60,3.05,3.15,2.0,1.0,0.00,0.00,1.9844
7,CCL220826C00007000,7.0,2.61,2.59,2.65,23.0,4.0,0.15,6.10,1.9063
8,CCL220826C00007500,7.5,2.14,2.11,2.16,46.0,3.0,-0.27,-11.20,1.6719
9,CCL220826C00008000,8.0,1.62,1.61,1.67,223.0,5.0,0.15,10.20,1.3594
10,CCL220826C00008500,8.5,1.08,1.13,1.17,205.0,7.0,0.13,13.68,1.0547
11,CCL220826C00009000,9.0,0.65,0.67,0.71,873.0,83.0,0.09,16.07,0.8242
12,CCL220826C00009500,9.5,0.33,0.33,0.33,2589.0,2131.0,0.08,32.00,0.7227
13,CCL220826C00010000,10.0,0.12,0.12,0.13,25990.0,4900.0,0.00,0.00,0.7031
14,CCL220826C00010500,10.5,0.04,0.04,0.05,6794.0,2018.0,-0.01,-20.00,0.7422
15,CCL220826C00011000,11.0,0.02,0.02,0.03,7666.0,882.0,-0.01,-33.33,0.8594
16,CCL220826C00011500,11.5,0.01,0.01,0.02,3179.0,135.0,-0.01,-50.00,0.9688
17,CCL220826C00012000,12.0,0.01,0.00,0.01,6976.0,292.0,0.00,0.00,0.9688
18,CCL220826C00012500,12.5,0.01,0.00,0.01,1534.0,100.0,0.00,0.00,1.1250
19,CCL220826C00013000,13.0,0.01,0.00,0.01,5569.0,11.0,0.00,0.00,1.2500
20,CCL220826C00013500,13.5,0.02,0.00,0.02,249.0,2.0,0.00,0.00,1.5000
21,CCL220826C00014000,14.0,0.02,0.00,0.02,248.0,3.0,0.00,0.00,1.6563
22,CCL220826C00014500,14.5,0.01,0.00,0.01,207.0,20.0,0.00,0.00,1.6250
23,CCL220826C00015000,15.0,0.01,0.00,0.01,386.0,10.0,0.00,0.00,1.7500
24,CCL220826C00015500,15.5,0.01,0.00,0.01,221.0,105.0,0.00,0.00,1.8750
25,CCL220826C00016000,16.0,0.01,0.00,0.01,122.0,3.0,0.00,0.00,1.9375
26,CCL220826C00017000,17.0,0.02,0.00,0.03,450.0,290.0,0.00,0.00,2.4688
27,CCL220826C00017500,17.5,0.02,0.00,0.03,696.0,569.0,0.00,0.00,2.5625